server:
  port: 9010

spring:
  application:
    name: haochang-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      dashboard: 127.0.0.1:8080


management:
  endpoints:
    web:
      exposure:
        include: "*"
